info:
  name: Update Cache Config
  type: http
  seq: 13

http:
  method: put
  url: "{{baseUrl}}/api/config/cache"
  headers:
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "stream_list_ttl_seconds": 300,
        "play_result_ttl_seconds": 3600,
        "meta_ttl_seconds": 86400
      }
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
