info:
  name: Update Streaming Defaults
  type: http
  seq: 17

http:
  method: put
  url: "{{baseUrl}}/api/config/defaults"
  headers:
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "quality": "1080p",
        "source_type": ["web-dl", "webrip"],
        "source": "AIOStreams",
        "audio_lang": "en",
        "min_size": 0,
        "max_size": 0,
        "min_bitrate": 0,
        "max_bitrate": 0
      }
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
